// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKNxEe5kRX_clp6vZoK7SiWRCwIciG-Ks',
    appId: '1:71179252973:android:288068dd779989856a88e4',
    messagingSenderId: '71179252973',
    projectId: 'smartbuildings-2a954',
    databaseURL:
        'https://smartbuildings-2a954-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbuildings-2a954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnljFihhQQD4z731hWDDDcq-JqrSttAJA',
    appId: '1:71179252973:ios:89e00fa04ba75a0a6a88e4',
    messagingSenderId: '71179252973',
    projectId: 'smartbuildings-2a954',
    databaseURL:
        'https://smartbuildings-2a954-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbuildings-2a954.appspot.com',
    iosClientId:
        '71179252973-4sauhm39ais00avmdkpmjq903i8ne13s.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartbuilding',
  );
}
